### ISSUE TITLE
Not connected to the mobile network, status 2 (searching)

### ISSUE THREAD

**Issue by elisgjana** [mongoose-os-libs/pppos#19]
I recently purchased the Module NB-IoT from the website https://docs.m5stack.com/#/en/module/nb-iot ,  because I want to connect it with esp32. I made the connections right by using the UART2. The configuration is like below: 

 ```
- ["pppos.enable", true]
 - ["pppos.uart_no", 2]
 - ["pppos.baud_rate", 115200]
 - ["pppos.fc_enable", false]
 - ["pppos.apn", "iot.1nce.net"]
 - ["pppos.user", ""]
 - ["pppos.pass", ""]
 - ["pppos.connect_on_startup", true]
 - ["pppos.connect_cmd", "ATDT*99***1#"]
 - ["pppos.echo_interval", 10]
 - ["pppos.echo_fails", 3]
 - ["pppos.hexdump_enable", true]
```
The SIM card that I am using is from an IOT company called "1NCE" (https://1nce.com/), powered by Telekom. My current location is Germany. After checking the logs, I see that SIM Card is recognized successfully, and it prints all the information including IMSI, ICCID and more. The problem stands that it does not connect to the mobile network, with status 2 (searching). When I try the SIM in my phone, everything is working. Below I am showing some of the logs:

<img width="607" alt="logs" src="https://user-images.githubusercontent.com/45203732/85950701-a84e7580-b95e-11ea-8b46-da6d8f1751b0.png">

**Comment by rojer** [comment]
i think this means that NB-IoT is not supported in your area, by your sim or your carrier.
Nb-IoT is completely different technology from the one used by your phone. if you need regular cellullar connectivity, you need a SIM-800 shield for m5stack (look it up).
