### ISSUE TITLE
PPPoS works with open broker, but not with AWS IOT (SIM800L)

### ISSUE THREAD

**Issue by ashwinpromethean** [mongoose-os-libs/pppos#4]
Hi,

I am trying to connect ESP32 to the internet using a SIM800L. I have tried connecting to a few open source brokers on port 1883 (like iot.eclipse.org), and it works well. But the moment I try to connect to AWS-IOT, it stops connecting and PPP starts disconnecting. Note that I am able to connect to AWS IOT over Wifi easily.

**The console output i get are as follows after restart :** 
[Aug 18 15:31:04.919] mgos_ota_http_client Init done, ota_lib=(null), ota handler 1
[Aug 18 15:31:04.926] mgos_ota_shadow_init OTA over shadow initialised
[Aug 18 15:31:04.932] mgos_wifi_setup      WiFi mode: off
[Aug 18 15:31:04.942] mgos_http_server_ini HTTP server started on [80]
[Aug 18 15:31:04.942] mgos_pppos_create    PPPoS UART2, 9600, fc off, APN 'internet'
[Aug 18 15:31:04.953] mgos_provision_init  Factory reset via button: pin 0 (enabled), hold_ms 0 (reset on reboot)
[Aug 18 15:31:04.973] button_timer_cb      Button released, NOT resetting
[Aug 18 15:31:04.974] mg_rpc_channel_mqtt  0x3ffb0b00 esp32_1D1CD0/rpc
[Aug 18 15:31:04.981] mg_rpc_channel_uart  0x3ffb0f74 UART0
[Aug 18 15:31:04.990] mgos_init            Init done, RAM: 226188 total, 177848 free, 175572 min free
[Aug 18 15:31:05.298] LED GPIO: 21 button GPIO: 0 
[Aug 18 15:31:05.306] mgos_aws_shadow_init Device shadow name: esp32_1D1CD0 (token b5b66125)
[Aug 18 15:31:05.313] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:31:05.322] mongoose_poll        New heap free LWM: 155800
[Aug 18 15:31:05.322] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:31:07.722] mgos_net_on_change_c PPP: connecting
[Aug 18 15:31:10.754] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:31:10.754] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:31:10.764] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:31:13.263] mgos_net_on_change_c PPP: connecting
[Aug 18 15:31:13.835] mgos_net_on_change_c PPP: connected
[Aug 18 15:31:13.835] mgos_pppos_uart_disp Starting PPP, user ''
[Aug 18 15:31:13.844] mongoose_poll        New heap free LWM: 151592
[Aug 18 15:31:16.925] mongoose_poll        New heap free LWM: 151372
[Aug 18 15:31:16.931] mongoose_poll        New heap free LWM: 151296 
[Aug 18 15:32:26.195] mgos_pppos_status_cb Error 6 (phase 0), reconnect
[Aug 18 15:32:26.195] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:32:26.206] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:32:28.613] mgos_net_on_change_c PPP: connecting
[Aug 18 15:32:31.645] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:32:31.645] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:32:31.655] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:32:34.154] mgos_net_on_change_c PPP: connecting
[Aug 18 15:32:37.226] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:32:37.226] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...

**The hexdump looks like this :** 
[Aug 18 15:37:06.449] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:37:06.459] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:37:08.957] mgos_net_on_change_c PPP: connecting
[Aug 18 15:37:08.989] 0000  5d d6 7e 0d 0a 4e                                ].~..N
[Aug 18 15:37:11.990] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:37:11.990] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:37:12.000] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:37:14.418] mgos_net_on_change_c PPP: connecting
[Aug 18 15:37:14.450] 0000  4f 20 43 41 52 52                                O CARR
[Aug 18 15:37:17.450] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:37:17.450] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:37:17.460] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:37:19.959] mgos_net_on_change_c PPP: connecting
[Aug 18 15:37:19.990] 0000  49 45 52 0d 0a 0d                                IER...
[Aug 18 15:37:23.021] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:37:23.021] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:37:23.031] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:37:25.529] mgos_net_on_change_c PPP: connecting
[Aug 18 15:37:25.561] 0000  0a 4f 4b 0d 0a 0d                                .OK...
[Aug 18 15:37:25.593] 0000  0a 4f 4b 0d 0a 0d                                .OK...
[Aug 18 15:37:25.628] 0000  0a 4f 4b 0d 0a 0d 0a 4f 4b 0d 0a                 .OK....OK..
[Aug 18 15:37:25.691] 0000  0a 0d 0a 4f 4b 0d 0a                             ...OK..
[Aug 18 15:37:25.737] 0000  0a 0d 0a 4f 4b 0d 0a 0d 0a 4f 4b 0d              ...OK....OK.
[Aug 18 15:37:25.745] mgos_pppos_uart_disp Starting PPP, user ''
[Aug 18 15:37:25.750] 0000  7e ff 7d 23 c0 21 7d 21 7d 21 7d 20 7d 34 7d 22  ~.}#.!}!}!} }4}"
[Aug 18 15:37:25.756] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 27  }&} } } } }%}&}'
[Aug 18 15:37:25.763] 0020  af 34 4b 7d 27 7d 22 7d 28 7d 22 f9 20 7e        .4K}'}"}(}". ~
[Aug 18 15:37:25.769] mongoose_poll        New heap free LWM: 150796
[Aug 18 15:37:25.776] mgos_net_on_change_c PPP: connected
[Aug 18 15:37:25.872] 0000  0a 0d 0a 4f 4b 0d 0a 0d 0a 4f 4b 0d 0a 0d 0a 4f  ...OK....OK....O
[Aug 18 15:37:25.878] 0010  4b 0d 0a 0d 0a 4f 4b 0d 0a 0d 0a 4f 4b 0d 0a 0d  K....OK....OK...
[Aug 18 15:37:25.884] 0020  0a 4f 4b 0d 0a 41 54 45                          .OK..ATE
[Aug 18 15:37:25.891] 0000  30 0d 0d 0a 4f 4b 0d 0a 0d 0a 4f 4b 0d 0a 0d 0a  0...OK....OK....
[Aug 18 15:37:25.897] 0010  43 4f 4e 4e                                      CONN
[Aug 18 15:37:25.904] 0000  45 43 54 0d 0a 7e ff 7d 23 c0 21 7d              ECT..~.}#.!}
[Aug 18 15:37:28.865] 0000  21 7d 21 7d 20 7d 32 7d 22 7d 26 7d 20 7d 2a 7d  !}!} }2}"}&} }*}
[Aug 18 15:37:28.871] 0010  20 7d 20 7d 23 7d 24 c0 23 7d 27 7d 22 7d 28 7d   } }#}$.#}'}"}(}
[Aug 18 15:37:28.877] 0020  22 55 83 7e 7e ff 7d 23                          "U.~~.}#
[Aug 18 15:37:28.884] 0000  7e ff 7d 23 c0 21 7d 24 7d 21 7d 20 7d 28 7d 23  ~.}#.!}$}!} }(}#
[Aug 18 15:37:28.890] 0010  7d 24 c0 23 2c d4 7e                             }$.#,.~
[Aug 18 15:37:28.897] mongoose_poll        New heap free LWM: 147368
[Aug 18 15:37:28.904] 0000  c0 21 7d                                         .!}
[Aug 18 15:37:28.980] 0000  23 7d 21 7d 20 7d 2a 7d 22 7d 26 7d 20 7d 2a 7d  #}!} }*}"}&} }*}
[Aug 18 15:37:28.986] 0010  20 7d 20 6c 50 7e 7e ff 7d 23 c0 21 7d 21 7d 21   } lP~~.}#.!}!}!
[Aug 18 15:37:28.992] 0020  7d 20 7d 32 7d                                   } }2}
[Aug 18 15:37:28.999] 0000  7e ff 7d 23 c0 21 7d 21 7d 22 7d 20 7d 34 7d 22  ~.}#.!}!}"} }4}"
[Aug 18 15:37:29.005] 0010  7d 26 7d 20 7d 2a 7d 20 7d 20 7d 25 7d 26 7d 27  }&} }*} } }%}&}'
[Aug 18 15:37:29.011] 0020  af 34 4b 7d 27 7d 22 7d 28 7d 22 7d 21 bb 7e     .4K}'}"}(}"}!.~
[Aug 18 15:37:29.018] mongoose_poll        New heap free LWM: 147332
[Aug 18 15:37:29.120] 0000  22 7d 26 7d 20 7d 2a 7d 20 7d 20 7d 23 7d 24 c0  "}&} }*} } }#}$.
[Aug 18 15:37:29.126] 0010  23 7d 27 7d 22 7d 28 7d 22 55 83 7e 7e ff 7d 23  #}'}"}(}"U.~~.}#
[Aug 18 15:37:29.132] 0020  c0 21 7d 21 7d                                   .!}!}
[Aug 18 15:37:29.138] 0000  7e ff 7d 23 c0 21 7d 24 7d 21 7d 20 7d 28 7d 23  ~.}#.!}$}!} }(}#
[Aug 18 15:37:29.145] 0010  7d 24 c0 23 2c d4 7e                             }$.#,.~
[Aug 18 15:37:29.152] 0000  22 7d 20 7d 2e 7d 22 7d 26                       "} }.}"}&
[Aug 18 15:37:31.961] 0000  7d 20 7d 2a 7d 20 7d 20 7d 27 7d 22 7d 28 7d 22  } }*} } }'}"}(}"
[Aug 18 15:37:31.967] 0010  d0 d3 7e 7e ff 7d 23 c0 21 7d 22 7d 22 7d        ..~~.}#.!}"}"}
[Aug 18 15:37:31.973] 0000  7e ff 7d 23 c0 21 7d 22 7d 22 7d 20 7d 2e 7d 22  ~.}#.!}"}"} }.}"
[Aug 18 15:37:31.980] 0010  7d 26 7d 20 7d 2a 7d 20 7d 20 7d 27 7d 22 7d 28  }&} }*} } }'}"}(
[Aug 18 15:37:31.986] 0020  7d 22 ee 50 7e                                   }".P~
[Aug 18 15:37:31.993] 0000  20 7d 34 7d 22 7d 26                              }4}"}&
[Aug 18 15:37:32.057] 0000  7d 20 7d 2a 7d 20 7d 20 7d 25                    } }*} } }%
[Aug 18 15:37:35.049] 0000  7d 26 7d 27 af 34 4b 7d 27 7d                    }&}'.4K}'}
[Aug 18 15:37:35.055] 0000  7e ff 7d 23 c0 21 7d 21 7d 22 7d 20 7d 34 7d 22  ~.}#.!}!}"} }4}"
[Aug 18 15:37:35.061] 0010  7d 26 7d 20 7d 2a 7d 20 7d 20 7d 25 7d 26 7d 27  }&} }*} } }%}&}'
[Aug 18 15:37:35.067] 0020  af 34 4b 7d 27 7d 22 7d 28 7d 22 7d 21 bb 7e     .4K}'}"}(}"}!.~
[Aug 18 15:37:38.039] 0000  22 7d 28 7d 22 ea d2 7e 7e ff                    "}(}"..~~.
[Aug 18 15:37:38.046] 0000  7e ff 03 c0 21 09 00 00 08 07 af 34 4b 9f 51 7e  ~...!......4K.Q~
[Aug 18 15:37:38.053] 0000  7e ff 03 80 21 01 01 00 1c 02 06 00 2d 0f 01 03  ~...!.......-...
[Aug 18 15:37:38.059] 0010  06 00 00 00 00 81 06 00 00 00 00 83 06 00 00 00  ................
[Aug 18 15:37:38.065] 0020  00 55 15 7e                                      .U.~
[Aug 18 15:37:38.071] 0000  7e ff 03 80 57 01 01 00 0e 01 0a e8 ef f9 36 e4  ~...W.........6.
[Aug 18 15:37:38.078] 0010  4d 72 05 01 fa 7e                                Mr...~
[Aug 18 15:37:38.084] mongoose_poll        New heap free LWM: 147312
[Aug 18 15:37:38.191] 0000  7d 23 c0 21 7d 21 7d 22 7d 20 7d 2e 7d 22 7d 26  }#.!}!}"} }.}"}&
[Aug 18 15:37:38.198] 0000  7d 20 7d 2a 7d 20 7d                             } }*} }
[Aug 18 15:37:38.205] 0000  20 7d 27 7d 22 7d 28                              }'}"}(
[Aug 18 15:37:38.212] 0000  7d 22 d0 d3 7e 7e                                }"..~~
[Aug 18 15:37:38.219] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:37:38.225] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:37:38.231] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:37:38.238] 0000  7e ff 7d 23 c0 21 7d 22 7d 22 7d 20 7d 2e 7d 22  ~.}#.!}"}"} }.}"
[Aug 18 15:37:38.244] 0010  7d 26 7d 20 7d 2a 7d 20 7d 20 7d 27 7d 22 7d 28  }&} }*} } }'}"}(
[Aug 18 15:37:38.250] 0020  7d 22 ee 50 7e                                   }".P~
[Aug 18 15:37:38.257] 0000  80 21 01 01 00 04 bb 99 7e 7e 80 21 01 01 00 04  .!......~~.!....
[Aug 18 15:37:38.264] 0010  bb 99 7e 7e 80 21 01 01                          ..~~.!..
[Aug 18 15:37:38.371] 0000  00 04 bb 99 7e 7e ff 03 c0 21 0a 00 00 08 00 00  ....~~...!......
[Aug 18 15:37:38.378] 0000  00 00 6b e4 7e 7e 80 21                          ..k.~~.!
[Aug 18 15:37:38.386] 0000  04 01 00 0a 02 06 00                             .......
[Aug 18 15:37:38.393] 0000  2d 0f 01 f8 30 7e 7e                             -...0~~
[Aug 18 15:37:38.400] 0000  ff 03 c0 21 08 00 00                             ...!...
[Aug 18 15:37:38.407] 0000  14 80 57 01 01 00                                ..W...
[Aug 18 15:37:38.416] 0000  0e                                               .
[Aug 18 15:37:41.392] 0000  01 0a e8 ef f9 36 e4 4d 72 05 c0 b4 7e 7e ff 03  .....6.Mr...~~..
[Aug 18 15:37:41.398] 0010  c0 21 01 03 00 0e 02 06 00 0a 00 00 07 02 08 02  .!..............
[Aug 18 15:37:41.404] 0020  7d 5d d6 7e 7e ff                                }].~~.
[Aug 18 15:37:41.411] 0000  7e ff 7d 23 c0 21 7d 22 7d 23 7d 20 7d 2e 7d 22  ~.}#.!}"}#} }.}"
[Aug 18 15:37:41.417] 0010  7d 26 7d 20 7d 2a 7d 20 7d 20 7d 27 7d 22 7d 28  }&} }*} } }'}"}(
[Aug 18 15:37:41.423] 0020  7d 22 43 55 7e                                   }"CU~
[Aug 18 15:37:44.243] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:37:44.249] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:37:44.255] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:37:50.254] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:37:50.260] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:37:50.266] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:37:56.265] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:37:56.271] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:37:56.277] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:02.275] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:02.281] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:02.287] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:08.271] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:08.292] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:08.298] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:14.297] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:14.303] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:14.309] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:20.307] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:20.313] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:20.319] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:26.319] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:26.325] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:26.331] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:32.329] 0000  7e ff 7d 23 c0 21 7d 21 7d 23 7d 20 7d 34 7d 22  ~.}#.!}!}#} }4}"
[Aug 18 15:38:32.335] 0010  7d 26 7d 20 7d 20 7d 20 7d 20 7d 25 7d 26 7d 24  }&} } } } }%}&}$
[Aug 18 15:38:32.341] 0020  59 ea 68 7d 27 7d 22 7d 28 7d 22 7d 2a 4a 7e     Y.h}'}"}(}"}*J~
[Aug 18 15:38:38.341] mgos_pppos_status_cb Error 6 (phase 0), reconnect
[Aug 18 15:38:38.341] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:38:38.352] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:38:40.551] 0000  7d 23 c0                                         }#.
[Aug 18 15:38:40.551] 0000  21 7d 23 7d 23 7d                                !}#}#}
[Aug 18 15:38:40.558] 0000  20 7d 2a 7d 22                                    }*}"
[Aug 18 15:38:40.770] mgos_net_on_change_c PPP: connecting
[Aug 18 15:38:40.801] 0000  7d 26 7d 20 7d 2a                                }&} }*
[Aug 18 15:38:43.832] mgos_pppos_uart_disp Command timed out: ATH
[Aug 18 15:38:43.832] mgos_pppos_uart_disp Connecting (UART2, APN 'internet')...
[Aug 18 15:38:43.842] mgos_net_on_change_c PPP: disconnected
[Aug 18 15:38:46.340] mgos_net_on_change_c PPP: connecting
[Aug 18 15:38:46.371] 0000  7d 20 7d 20 96 cb                                } } ..

I have to reiterate that this works over wifi, but the moment i change to PPP, it stops connecting.

The PPPoS config looks like this
  "pppos": {
    "enable": true,
    "uart_no": 2,
    "baud_rate": 9600,
    "fc_enable": false,
    "apn": "internet",
    "user": "",
    "pass": "",
    "connect_cmd": "ATDT*99***1#",
    "echo_interval": 10,
    "echo_fails": 3,
    "hexdump_enable": true
  }

What would be the issue here?

**Comment by nicoloboatto** [comment]
Did you manage to get this working, by any chance?

**Comment by rojer** [comment]
a lot of work happened lately to get connection stable, closing.
