### ISSUE TITLE
SMS / Call

### ISSUE THREAD

**Issue by thbl** [mongoose-os-libs/pppos#6]
Is it possible to send / receive sms / calls somehow while using pppos ?

**Comment by rojer** [comment]
there is no API to send an SMS as such but there is an API to send custom commands which should work while ppp is active [ mgos_pppos_send_cmd()](https://github.com/mongoose-os-libs/pppos/blob/master/include/mgos_pppos.h#L51).

**Comment by thbl** [comment]
So with mgos_pppos_send_cmd we can execute normal AT commands ?
-I see in source it only reply true/false, is there a way to listen for the AT response ? (to check signal / check for new sms)

**Comment by rojer** [comment]
the return value is actually just acnowledged that command was ququed, actual result is delivered via the MGOS_PPPOS_CMD_RESP event.
